const resources = {
  en: {
    translation: {
      "label_loading": "Loading...",
      "label_item": "Item",
      "title_app": "we compare prices",
      "nav_home": "Home",
      "nav_yourlist": "Your list",
      "nav_aboutus": "About us",
      "nav_privacy": "Privacy policy",
      "nav_install": "How to install",
      "button_new_product": "New Product",
      "button_update_price": "Update Price",
      "label_search": "Search",
      "button_copy": "Copy",
      "button_back": "Back",
      "label_name": "Name",
      "label_store": "Store",
      "label_price": "Price",
      "label_posted": "Posted",
      "label_coupon": "Coupon",
      "label_bulk": "Bulk",
      "label_selected": "Selected",
      "label_more": "Details",
      "help_name": "If product already exists open its history and update price",
      "help_store": "Keep store name consistent",
      "help_decimal": "Use dot as decimal point",
      "help_membership": "Members price",
      "help_bulk": "Price in bulk",
      "button_cancel": "Cancel",
      "button_save": "Save",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/pricey/data/privacy-policy-en",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png",
      "meta_description": "we compare grocery prices - see how much it was a week, month or even a year ago - get on your iPhone/Android",
      "meta_keywords": "shops, deals, price, app, market, iphone, apple, android, samsung, application, pwa",
      "message_warning": "Data seen in this app is for information purposes only and is not meant to be used in trade. Join us on tiktok.com/@czarna.marchewka and discover all the features. We use cookies for personalisation, read our Privacy Policy.",
      "button_gotit": "Got it"
    }
  },
  pl: {
    translation: {
      "label_loading": "Wczytuję...",
      "label_item": "Produkt",
      "title_app": "porównujemy ceny",
      "nav_home": "Strona główna",
      "nav_yourlist": "Twoja lista",
      "nav_aboutus": "O nas",
      "nav_privacy": "Polityka prywatności",
      "nav_install": "Jak zainstalować",
      "button_new_product": "Nowy produkt",
      "button_update_price": "Aktualizuj cenę",
      "label_search": "Szukaj",
      "button_copy": "Kopiuj",
      "button_back": "Powrót",
      "label_name": "Nazwa",
      "label_store": "Sklep",
      "label_price": "Cena",
      "label_posted": "Dodano",
      "label_coupon": "Z kartą",
      "label_bulk": "Kilka",
      "label_selected": "Wybrane",
      "label_more": "Historia",
      "help_name": "Jeśli produkt istnieje otwórz jego historię i zaktualizuj cenę",
      "help_store": "Utrzymuj nazwy sklepów jednakowe",
      "help_decimal": "Użyj kropki jako przecinka",
      "help_membership": "Cena z kartą",
      "help_bulk": "Przy zakupie większej ilości",
      "button_cancel": "Zaniechaj",
      "button_save": "Zachowaj",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/pricey/data/privacy-policy-pl",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/pl_badge_web_generic.png",
      "meta_description": "porównujemy ceny pomiędzy sklepami - zobacz ile produkt kosztował tydzień, miesiąc, a nawet rok temu - zainstaluj na iPhone/Android",
      "meta_keywords": "zakupy, promocje, porównaj, cena, aplikacja, sklep, market, tydzień, miesiąc, rok, iphone, apple, android, samsung, apka, pwa",
      "message_warning": "Dane prezentowane w aplikacji mają charakter wyłącznie informacyjny. Dołącz do nas na tiktok.com/@czarna.marchewka aby odkryć wszystkie funkcje. Pliki cookies są wykorzystywane do personalizacji, a szczegóły znajdziesz w Polityce Prywatności.",
      "button_gotit": "Wchodzę"
    }
  }
}
