-- ALTER TABLE `CENA` AUTO_INCREMENT = 1;

-- DROP TRIGGER `CENA_DODANO_DEFAULT`;

-- DROP TABLE `CENA`;

/**/ CREATE TABLE `CENA` (
  `ID` BIGINT AUTO_INCREMENT,
  `PRODUKT` VARCHAR(1024) NOT NULL,
  `SKLEP` VARCHAR(1024) NOT NULL,
  `CENA` FLOAT NOT NULL,
  `KRAJ` VARCHAR(5) NOT NULL,
  `UZYTKOWNIK` VARCHAR(36) NOT NULL,
  `DODANO` DATETIME,
  `COUPON` TINYINT(1),
  `BULK` TINYINT(1),
  CONSTRAINT `PK_Cena` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `CENA_DODANO_DEFAULT` BEFORE INSERT ON `CENA`
/*--*/   FOR EACH ROW SET NEW.`DODANO` = CURRENT_TIMESTAMP;


-- ALTER TABLE `VISIT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `VISIT_DODANO_DEFAULT`;

-- DROP TABLE `VISIT`;

/**/ CREATE TABLE `VISIT` (
  `ID` BIGINT AUTO_INCREMENT,
  `ADDRESS` VARCHAR(15) NOT NULL,
  `CLIENT` VARCHAR(1024) NOT NULL,
  `COUNTRY` VARCHAR(5) NOT NULL,
  `CREATED` DATETIME,
  CONSTRAINT `PK_Visit` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `VISIT_CREATED_DEFAULT` BEFORE INSERT ON `VISIT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;
