-- ALTER TABLE `EVENT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `EVENT_CREATED_DEFAULT`;

-- DROP TABLE `EVENT`;

/**/ CREATE TABLE `EVENT` (
  `ID` BIGINT AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(1024),
  `START` DATETIME NOT NULL,
  `PERIOD` FLOAT,
  `TYPE` VARCHAR(15),
  `CONFIRMED` TINYINT(1),
  `NOTES` VARCHAR(1024),
  `ADDRESS` VARCHAR(15),
  `TENANT` VARCHAR(36) NOT NULL,
  `CREATED` DATETIME,
  CONSTRAINT `PK_Event` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `EVENT_CREATED_DEFAULT` BEFORE INSERT ON `EVENT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `TENANT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `TENANT_CREATED_DEFAULT`;

-- DROP TABLE `TENANT`;

/**/ CREATE TABLE `TENANT` (
  `ID` BIGINT AUTO_INCREMENT,
  `NAME` VARCHAR(36) NOT NULL,
  `DESCRIPTION` VARCHAR(1024),
  `TYPE` VARCHAR(15),
  `ACTIVE` TINYINT(1),
  `UNTIL` DATETIME,
  `VALUE` FLOAT,
  `NOTES` VARCHAR(1024),
  `ADDRESS` VARCHAR(15) NOT NULL,
  `CREATED` DATETIME,
  `PASSWORD` VARCHAR(255) NOT NULL,
  CONSTRAINT `PK_Tenant` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `TENANT_CREATED_DEFAULT` BEFORE INSERT ON `TENANT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `SETTINGS` AUTO_INCREMENT = 1;

-- DROP TRIGGER `SETTINGS_CREATED_DEFAULT`;

-- DROP TABLE `SETTINGS`;

/**/ CREATE TABLE `SETTINGS` (
  `ID` BIGINT AUTO_INCREMENT,
  `SCHEDULE` VARCHAR(1024),
  `SHOWVISITS` TINYINT(1),
  `SHOWBOOKING` TINYINT(1),
  `TENANT` VARCHAR(36) NOT NULL,
  CONSTRAINT `PK_Settings` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `SETTINGS_CREATED_DEFAULT` BEFORE INSERT ON `SETTINGS`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `LOGBOOK` AUTO_INCREMENT = 1;

-- DROP TRIGGER `LOGBOOK_ADDED_DEFAULT`;

-- DROP TABLE `LOGBOOK`;

/**/ CREATE TABLE `LOGBOOK` (
  `ID` BIGINT AUTO_INCREMENT,
  `ADDRESS` VARCHAR(15) NOT NULL,
  `CLIENT` VARCHAR(1024) NOT NULL,
  `COUNTRY` VARCHAR(5) NOT NULL,
  `CREATED` DATETIME,
  CONSTRAINT `PK_Logbook` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `LOGBOOK_CREATED_DEFAULT` BEFORE INSERT ON `LOGBOOK`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `CLIENT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `CLIENT_CREATED_DEFAULT`;

-- DROP TABLE `CLIENT`;

/**/ CREATE TABLE `CLIENT` (
  `ID` BIGINT AUTO_INCREMENT,
  `NAME` VARCHAR(36) NOT NULL,
  `DISPLAYNAME` VARCHAR(255),
  `TYPE` VARCHAR(15),
  `ACTIVE` TINYINT(1),
  `UNTIL` DATETIME,
  `CREATED` DATETIME,
  `PASSWORD` VARCHAR(255) NOT NULL,
  CONSTRAINT `PK_Client` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `CLIENT_CREATED_DEFAULT` BEFORE INSERT ON `CLIENT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `ASSIGNMENT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `ASSIGNMENT_ADDED_DEFAULT`;

-- DROP TABLE `ASSIGNMENT`;

/**/ CREATE TABLE `ASSIGNMENT` (
  `ID` BIGINT AUTO_INCREMENT,
  `EVENT_ID` BIGINT NOT NULL,
  `CLIENT_ID` BIGINT NOT NULL,
  `ACCEPTED` TINYINT(1),
  `ADDRESS` VARCHAR(15) NOT NULL,
  `CLIENT` VARCHAR(1024) NOT NULL,
  `COUNTRY` VARCHAR(5) NOT NULL,
  `CREATED` DATETIME,
  CONSTRAINT `PK_Assignment` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `ASSIGNMENT_CREATED_DEFAULT` BEFORE INSERT ON `ASSIGNMENT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;
