const resources = {
  en: {
    translation: {
      "title_home": "wlap.pl",
      "description_copyright": "wlap.pl, 2025",
      "description_guide": "",
      "button_backtotop": "Back to top",
      "button_home": "Home",
      "title_contact": "Custom orders and questions",
      "subtitle_contact": "Contact",
      "description_contact": "Questions or custom orders see Contant section",
      "link_emailus": "Email us",
      "title_products": "Mobile and web apps",
      "description_products": "We create mobile apps for Android and web apps that you can run on any platform with access to the internet",
      "button_googleplay": "Google Play",
      "button_howto": "How to",
      "button_online": "Online",
      "button_get": "Install",
      "name_pricey": "Pricey",
      "description_pricey": "Record grocery prices, invite your firends, check what others submit, look up the history or observe cost of living rise",
      "name_busstop": "BusStop",
      "description_busstop": "Bus schedule with map",
      "name_myparish": "My Parish",
      "description_myparish": "Find your church on a map, get the directions, read the bulletin, check the mass times or pray online",
      "name_talkietalkie": "TalkieTalkie",
      "description_talkietalkie": "Send and receive voice messages over WiFi between two phones without the network connection in Walkie-talkie style",
      "item_offer1": "",
      "item_offer2": "",
      "item_offer3": "",
      "item_offer4": "",
      "item_offer5": "",
      "item_offer6": "",
      "item_offer7": "",
      "button_back": "Back",
      "title_offer": "Offer",
      "subtitle_products": "Products",
      "subtitle_offer": "Services",
      "carousel_image": "Step no",
      "header_install": "How to install PWA applications",
      "description_install": "Select an item below to read installation steps in an exmaple browser on the selected platform. In other browsers this process looks simmilar but menu items and buttons might be named differently. The pictures on the side present the steps, use arrows to navigate.",
      "accordion_header_iphone": "iPhone (Safari)",
      "accordion_intro_iphone": "Open Safari and go to the address https://wlap.pl/",
      "accordion_contd1_iphone": "On the home page select the application you wish to install and open it (Step no 1)",
      "accordion_contd2_iphone": "Open browser menu and select 'Add to Home Screen' (Step no 2)",
      "accordion_contd3_iphone": "On the screen with application description select 'Add' (Step no 3)",
      "accordion_contd4_iphone": "Close Safari, on the Home Screen you will see the installed application icon (Step no 4)",
      "accordion_header_android": "Android (e.g. Chrome)",
      "accordion_intro_android": "Open Chrome and go to the address https://wlap.pl/",
      "accordion_contd1_android": "On the home page select the application you wish to install and open it (Step no 1)",
      "accordion_contd2_android": "Open browser menu and select 'Add to Home Screen' (Step no 2)",
      "accordion_contd3_android": "On the screen with application description select 'Install' (Step no 3)",
      "accordion_contd4_android": "Close Chrome, on the Home Screen you will see the installed application icon (Step no 4)",
      "accordion_header_windows": "Windows (e.g. Chrome)",
      "accordion_intro_windows": "Open Chrome and go to the address https://wlap.pl/",
      "accordion_contd1_windows": "On the home page select the application you wish to install and open it (Step no 1)",
      "accordion_contd2_windows": "Open browser menu and select 'Install ...' (Step no 2)",
      "accordion_contd3_windows": "On the screen with application description select 'Install' (Step no 3)",
      "accordion_contd4_windows": "Close Chrome, on the Taskbar you will see the installed application icon (Step no 4)"
    }
  },
  pl: {
    translation: {
      "title_home": "wlap.pl",
      "description_copyright": "wlap.pl, 2025",
      "description_guide": "",
      "button_backtotop": "W górę",
      "button_home": "Strona głowna",
      "title_contact": "Pytania i zamówienia",
      "subtitle_contact": "Kontakt",
      "description_contact": "Pytania oraz zlecenia proszę kierować na adres e-mail",
      "link_emailus": "Napisz do nas",
      "title_products": "O nas",
      "description_products": "tworzymy internetowe aplikacje mobilne na iPhone oraz Android",
      "button_googleplay": "Sklep Play",
      "button_howto": "Przewodnik",
      "button_online": "Przejdź",
      "button_get": "Pobierz",
      "name_pricey": "Cennik",
      "description_pricey": "porównujemy ceny pomiędzy sklepami - zobacz ile produkt kosztował tydzień, miesiąc a nawet rok temu - zainstaluj na iPhone/Android",
      "name_busstop": "BusStop",
      "description_busstop": "Rozkład jazdy autobusów z mapą",
      "name_myparish": "Parafia",
      "description_myparish": "mapa i wyszukiwarka kościołów, witryny parafii, cmentarze oraz prasa i transmisje eucharystii",
      "name_talkietalkie": "TalkieTalkie",
      "description_talkietalkie": "Wysyłaj i odbieraj wiadomości głosowe przy pomocy WiFi pomiędzy dwoma telefonami bez połączenia sieciowego w stylu Walkie-talkie",
      "item_offer1": "Aplikacje mobilne i internetowe",
      "item_offer2": "Rozszerzenia do Office, Chrome, Visual Studio Code itp",
      "item_offer3": "Zabezpieczanie połączeń sieciowych",
      "item_offer4": "Witryny internetowe",
      "item_offer5": "Rozkłady jazdy",
      "item_offer6": "Domowe sieci komputerowe",
      "item_offer7": "Testowanie rozwiązań informatycznych",
      "title_offer": "Oferta",
      "subtitle_products": "Produkty",
      "subtitle_offer": "Usługi",
      "button_back": "Powrót",
      "carousel_image": "Krok nr",
      "header_install": "Jak zainstalować aplikacje typu PWA",
      "description_install": "Poniżej przedstawiamy instrukcje instalacji na wybranych platformach przy użyciu przykładowych przeglądarek. Proces przebiega podobnie w innych przeglądarkach, różnić mogą się nazwy menu i przycisków. Obok obrazy pokazujące kolejne kroki, użyj strzałek aby przełączać.",
      "accordion_header_iphone": "iPhone (Safari)",
      "accordion_intro_iphone": "Uruchom Safari i przejdź pod adres https://wlap.pl/",
      "accordion_contd1_iphone": "Na stronie głównej wybierz aplikację którą chcesz zainstalować i przejdź do niej (Krok nr 1)",
      "accordion_contd2_iphone": "Otwórz menu przeglądarki i wybierz 'Dodaj do ekranu głównego' (Krok nr 2)",
      "accordion_contd3_iphone": "Na ekranie z opisem aplikacji wybierz 'Dodaj' (Krok nr 3)",
      "accordion_contd4_iphone": "Zamknij Safari, na ekranie głównym ujrzysz ikonę zainstalowanej aplikacji (Krok nr 4)",
      "accordion_header_android": "Android (Chrome)",
      "accordion_intro_android": "Uruchom Chrome i przejdź pod adres https://wlap.pl/",
      "accordion_contd1_android": "Na stronie głównej wybierz aplikację którą chcesz zainstalować i przejdź do niej (Krok nr 1)",
      "accordion_contd2_android": "Otwórz menu przeglądarki i wybierz 'Dodaj do ekranu głównego' (Krok nr 2)",
      "accordion_contd3_android": "Na ekranie z opisem aplikacji wybierz 'Zainstaluj' (Krok nr 3)",
      "accordion_contd4_android": "Zamknij Chrome, na ekranie głównym ujrzysz ikonę zainstalowanej aplikacji (Krok nr 4)",
      "accordion_header_windows": "Windows (Chrome)",
      "accordion_intro_windows": "Uruchom Chrome i przejdź pod adres https://wlap.pl/",
      "accordion_contd1_windows": "Na stronie głównej wybierz aplikację którą chcesz zainstalować i przejdź do niej (Krok nr 1)",
      "accordion_contd2_windows": "Otwórz menu przeglądarki i wybierz 'Zainstaluj ...' (Krok nr 2)",
      "accordion_contd3_windows": "W oknie dialogowym wybierz 'Zainstaluj' (Krok nr 3)",
      "accordion_contd4_windows": "Zamknij Chrome, na pasku zadań ujrzysz ikonę zainstalowanej aplikacji (Krok nr 4)"
    }
  }
}
