-- ALTER TABLE `EVENT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `EVENT_CREATED_DEFAULT`;

-- DROP TABLE `EVENT`;

/**/ CREATE TABLE `EVENT` (
  `ID` BIGINT AUTO_INCREMENT,
  `NAME` VARCHAR(255),
  `DESCRIPTION` VARCHAR(1024),
  `TYPE` VARCHAR(15),
  `SCHEDULED` DATETIME,
  `NOTES` VARCHAR(1024),
  `APPROVED` TINYINT(1),
  `CITY` VARCHAR(255),
  `POSTALCODE` VARCHAR(10),
  `STATE` VARCHAR(100),
  `COUNTRY` VARCHAR(100),
  `WEBSITE` VARCHAR(255),
  `CREATED` DATETIME,
  CONSTRAINT `PK_Event` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `EVENT_CREATED_DEFAULT` BEFORE INSERT ON `EVENT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `PERSON` AUTO_INCREMENT = 1;

-- DROP TRIGGER `PERSON_CREATED_DEFAULT`;

-- DROP TABLE `PERSON`;

/**/ CREATE TABLE `PERSON` (
  `ID` BIGINT AUTO_INCREMENT,
  `NAME` VARCHAR(36) NOT NULL,
  `DESCRIPTION` VARCHAR(1024),
  `SEX` TINYINT(1),
  `NOTES` VARCHAR(1024),
  `APPROVED` TINYINT(1),
  `PASSWORD` VARCHAR(255) NOT NULL,
  `CREATED` DATETIME,
  CONSTRAINT `PK_Person` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `PERSON_CREATED_DEFAULT` BEFORE INSERT ON `PERSON`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `LOGBOOK` AUTO_INCREMENT = 1;

-- DROP TRIGGER `LOGBOOK_ADDED_DEFAULT`;

-- DROP TABLE `LOGBOOK`;

/**/ CREATE TABLE `LOGBOOK` (
  `ID` BIGINT AUTO_INCREMENT,
  `ADDRESS` VARCHAR(15) NOT NULL,
  `CLIENT` VARCHAR(1024) NOT NULL,
  `COUNTRY` VARCHAR(5) NOT NULL,
  `CREATED` DATETIME,
  CONSTRAINT `PK_Logbook` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `LOGBOOK_CREATED_DEFAULT` BEFORE INSERT ON `LOGBOOK`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;
