const resources = {
  en: {
    translation: {}
  },
  pl: {
    translation: {
      "title_app": "zaplanuj pracę - grafik.wlap.pl",
      "label_toggle_navigation": "Nawigacja",
      "label_home": "Portal",
      "label_backtotop": "Do góry",
      "label_copyright": "wlap.pl (C)",
      "nav_aboutus": "Twórcy",
      "nav_privacy": "Polityka prywatności",
      "nav_install": "Zainstaluj aplikację",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/www/refs/heads/main/seo/privacy-policy-pl",
      "label_views": "Odwiedzin dzisiaj: ",
      "label_tenant": "Grupa",
      "label_client": "Klient",
      "label_try_title": "Wypróbuj za darmo!",
      "label_try_description": "Zapoznaj się z systemem bez podawania danych i reklam",
      "label_try_footer": "Wprowadź 'demo' jako klienta i 'demo' jako hasło poniżej i kliknij 'Zaloguj'",
      "label_please_sign_in": "Zaloguj się",
      "label_password": "Hasło",
      "label_tenant_password": "Hasło grupy",
      "label_remember_me": "Zapamiętaj",
      "label_sign_in": "Zaloguj",
      "label_signin_failure": "Niepoprawne hasło lub nazwa klienta!",
      "label_signout": "Wyloguj",
      "label_actions": "Akcje",
      "label_refresh": "Odśwież",
      "label_back": "Powrót",
      "label_close": "Zamknij",
      "label_delete": "Usuń",
      "label_delete_title": "Usunąć?",
      "label_cancel": "Zaniechaj",
      "label_ok": "OK",
      "label_save": "Zapisz",
      "label_title_confirm": "Potwierdź",
      "label_submit": "Potwierdź",
      "label_event": "Zaplanuj",
      "label_add_event": "Dodaj",
      "label_description": "Opis",
      "label_type": "Typ",
      "label_period": "Długość",
      "label_notes": "Notatki",
      "label_settings": "Ustawienia",
      "label_show_booking": "Wyświetlaj zapisy",
      "label_firstname": "Imię",
      "label_surname": "Nazwisko",
      "label_statistics": "Statystyki",
      "label_reader_header": "Zapisy",
      "label_reader_description": "",
      "label_contact": "Dane kontaktowe",
      "label_contact_title": "Kontakt",
      "label_contact_subtitle": "",
      "label_street": "Ulica",
      "label_number": "Numer domu",
      "label_city": "Miejscowość",
      "label_postalcode": "Kod pocztowy",
      "label_email": "e-mail",
      "label_phone": "Telefon",
      "label_iban": "IBAN",
      "label_starting": "Początek",
      "label_date": "Data",
      "label_nodate": "Brak daty",
      "label_weeks": "Tygodnie",
      "label_current_week": "Ten tydzień",
      "label_next_week": "Następny tydzień",
      "label_day": "Dzień",
      "label_month": "Miesiąc",
      "label_year": "Rok",
      "label_monday": "Poniedziałek",
      "label_tuesday": "Wtorek",
      "label_wednesday": "Środa",
      "label_thursday": "Czwartek",
      "label_friday": "Piątek",
      "label_saturday": "Sobota",
      "label_sunday": "Niedziela",
      "label_january": "styczeń",
      "label_february": "luty",
      "label_march": "marzec",
      "label_april": "kwiecień",
      "label_may": "maj",
      "label_june": "czerwiec",
      "label_july": "lipiec",
      "label_august": "sierpień",
      "label_september": "wrzesień",
      "label_october": "październik",
      "label_november": "listopad",
      "label_december": "grudzień"
    }
  }
}
