-- ALTER TABLE `SCHEDULED` AUTO_INCREMENT = 1;

-- DROP TRIGGER `SCHEDULED_CREATED_DEFAULT`;

-- DROP TABLE `SCHEDULED`;

/**/ CREATE TABLE `SCHEDULED` (
  `ID` BIGINT AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(1024),
  `SCHEDULED` DATETIME,
  `VALUE` FLOAT NOT NULL,
  `TYPE` VARCHAR(15),
  `BOOKED` TINYINT(1),
  `NOTES` VARCHAR(1024),
  `ADDRESS` VARCHAR(15) NOT NULL,
  `TENANT` VARCHAR(36) NOT NULL,
  `CREATED` DATETIME,
  CONSTRAINT `PK_Scheduled` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `SCHEDULED_CREATED_DEFAULT` BEFORE INSERT ON `SCHEDULED`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `TENANT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `TENANT_CREATED_DEFAULT`;

-- DROP TABLE `TENANT`;

/**/ CREATE TABLE `TENANT` (
  `ID` BIGINT AUTO_INCREMENT,
  `NAME` VARCHAR(36) NOT NULL,
  `DESCRIPTION` VARCHAR(1024),
  `TYPE` VARCHAR(15),
  `ACTIVE` TINYINT(1),
  `UNTIL` DATETIME,
  `VALUE` FLOAT,
  `NOTES` VARCHAR(1024),
  `ADDRESS` VARCHAR(15) NOT NULL,
  `CREATED` DATETIME,
  `PASSWORD` VARCHAR(255) NOT NULL,
  CONSTRAINT `PK_Tenant` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `TENANT_CREATED_DEFAULT` BEFORE INSERT ON `TENANT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;



-- ALTER TABLE `CONTACT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `CONTACT_CREATED_DEFAULT`;

-- DROP TABLE `CONTACT`;

/**/ CREATE TABLE `CONTACT` (
  `ID` BIGINT AUTO_INCREMENT,
  `STREET` VARCHAR(255),
  `NUMBER` VARCHAR(10),
  `CITY` VARCHAR(255),
  `POSTALCODE` VARCHAR(10),
  `STATE` VARCHAR(100),
  `COUNTRY` VARCHAR(100),
  `EMAIL` VARCHAR(255),
  `PHONE` VARCHAR(15),
  `IBAN` VARCHAR(28),
  `DESCRIPTION` VARCHAR(1024),
  `TYPE` VARCHAR(15),
  `TENANT` VARCHAR(36) NOT NULL,
  `ACTIVE` TINYINT(1),
  `CREATED` DATETIME,
  CONSTRAINT `PK_Contact` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `CONTACT_CREATED_DEFAULT` BEFORE INSERT ON `CONTACT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `VISIT` AUTO_INCREMENT = 1;

-- DROP TRIGGER `VISIT_CREATED_DEFAULT`;

-- DROP TABLE `VISIT`;

/**/ CREATE TABLE `VISIT` (
  `ID` BIGINT AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(20),
  `SURNAME` VARCHAR(50),
  `STREET` VARCHAR(255),
  `NUMBER` VARCHAR(10),
  `CITY` VARCHAR(255),
  `VALUE` FLOAT,
  `TENANT` VARCHAR(36) NOT NULL,
  `SHOW` TINYINT(1),
  `CREATED` DATETIME,
  CONSTRAINT `PK_Visit` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `VISIT_CREATED_DEFAULT` BEFORE INSERT ON `VISIT`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;


-- ALTER TABLE `SETTINGS` AUTO_INCREMENT = 1;

-- DROP TRIGGER `SETTINGS_CREATED_DEFAULT`;

-- DROP TABLE `SETTINGS`;

/**/ CREATE TABLE `SETTINGS` (
  `ID` BIGINT AUTO_INCREMENT,
  `SCHEDULE` VARCHAR(1024),
  `SHOWVISITS` TINYINT(1),
  `SHOWBOOKING` TINYINT(1),
  `TENANT` VARCHAR(36) NOT NULL,
  CONSTRAINT `PK_Settings` PRIMARY KEY (`ID`)
); /**/

/*--*/ CREATE TRIGGER `SETTINGS_CREATED_DEFAULT` BEFORE INSERT ON `SETTINGS`
/*--*/   FOR EACH ROW SET NEW.`CREATED` = CURRENT_TIMESTAMP;
