const resources = {
  en: {
    translation: {
      "title_app": "My Parish by wlap.pl",
      "see_link": "See",
      "list_schedule": "Schedule",
      "list_announcement": "Announcement",
      "list_contact": "Contact",
      "list_other": "Other",
      "list_live": "Live",
      "list_directions": "Route",
      "list_select": "Select",
      "nav_your": "Your",
      "nav_list": "List",
      "nav_map": "Map",
      "nav_news": "News",
      "nav_aboutus": "About us",
      "nav_privacy": "Privacy policy",
      "nav_install": "How to install",
      "nav_manage": "Manage",
      "label_search": "Search",
      "label_live": "Live",
      "label_active": "Active",
      "button_back": "Back",
      "overlay_active": "Active",
      "overlay_inactive": "Inactive",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/myparish/data/privacy-policy-en",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png",
      "meta_description": "Find your church on a map, get the directions, read the bulletin, check the mass times or pray online",
      "meta_keywords": "church, mass, map, app, catholic, parish, cemetery, live, iphone, apple, android, samsung, application, pwa",
      "label_missing": "Parish data missing"
    }
  },
  pl: {
    translation: {
      "title_app": "Kościoły",
      "see_link": "Strona parafii",
      "list_schedule": "Intencje",
      "list_announcement": "Ogłoszenia",
      "list_contact": "Kontakt",
      "list_other": "Cmentarz",
      "list_live": "Transmisja mszy",
      "list_directions": "Wytycz dojazd",
      "list_select": "Ustaw jako Moja Parafia",
      "nav_your": "Moja parafia",
      "nav_list": "Lista parafii",
      "nav_map": "Mapa parafii",
      "nav_news": "Zobacz także",
      "nav_aboutus": "Twórcy",
      "nav_privacy": "Polityka prywatności",
      "nav_install": "Zainstaluj aplikację",
      "nav_manage": "Zarządzaj parafią",
      "label_search": "Szukaj parafii",
      "label_live": "Transmisja mszy",
      "label_active": "Nadchodzące msze",
      "button_back": "Powrót",
      "overlay_active": "Nadchodzące msze",
      "overlay_inactive": "Pozostałe",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/myparish/data/privacy-policy-pl",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/pl_badge_web_generic.png",
      "meta_description": "mapa i wyszukiwarka kościołów, witryny parafii, cmentarze, prasa i transmisje online",
      "meta_keywords": "kościół, znajdź, msze, mapa, aplikacja, cmentarz, transmisja, katolicki, parafia, eucharystia, iphone, apple, android, samsung, apka, pwa",
      "label_missing": "Brak danych parafii",
      "label_monday": "Poniedziałek",
      "label_tuesday": "Wtorek",
      "label_wednesday": "Środa",
      "label_thursday": "Czwartek",
      "label_friday": "Piątek",
      "label_saturday": "Sobota",
      "label_sunday": "Niedziela",
      "label_contact_title": "Kontakt",
      "label_contact_subtitle": "",
      "label_phone": "Telefon",
      "label_iban": "IBAN",
      "label_emailus": "Napisz",
      "label_tenant": "Parafia",
      "label_toggle_navigation": "Nawigacja",
      "label_reader_header": "Msze święte",
      "label_reader_description": "",
      "label_scheduled": "Intencje",
      "label_description": "Opis",
      "label_order": "Zamów mszę",
      "label_book": "Zaproszenia na wizytę duszpasterską",
      "label_announcements": "Ogłoszenia",
      "label_from": "Od",
      "label_submit": "Potwierdź",
      "label_backtotop": "Do góry",
      "label_copyright": "wlap.pl (C)",
      "label_home": "Portal",
      "label_try_title": "Wypróbuj za darmo!",
      "label_try_description": "Zapoznaj się z systemem bez podawania danych i reklam",
      "label_try_footer": "Wprowadź 'swCharbel+Bejrut' jako parafię i 'demo' jako hasło poniżej i kliknij 'Zaloguj'",
      "label_please_sign_in": "Zaloguj się",
      "label_password": "Hasło",
      "label_remember_me": "Zapamiętaj",
      "label_sign_in": "Zaloguj",
      "label_signin_failure": "Niepoprawne hasło lub nazwa parafii!",
      "label_dashboard": "Kontakt",
      "label_street": "Ulica",
      "label_number": "Numer domu",
      "label_city": "Miejscowość",
      "label_postalcode": "Kod pocztowy",
      "label_email": "e-mail",
      "label_delete_title": "Usunąć?",
      "label_close": "Zamknij",
      "label_delete": "Usuń",
      "label_cancel": "Zaniechaj",
      "label_ok": "OK",
      "label_value": "Ofiara",
      "label_notes": "Notatki",
      "label_actions": "Akcje",
      "label_scheduled_event": "Intencje",
      "label_add_scheduled": "Dodaj",
      "label_current_week": "Ten tydzień",
      "label_next_week": "Następny tydzień",
      "label_year": "Rok",
      "label_visit": "Wizyta duszpasterska",
      "label_add_visit": "Dodaj",
      "label_settings": "Ustawienia",
      "label_signout": "Wyloguj",
      "label_contact": "Dane kontaktowe",
      "label_january": "styczeń",
      "label_february": "luty",
      "label_march": "marzec",
      "label_april": "kwiecień",
      "label_may": "maj",
      "label_june": "czerwiec",
      "label_july": "lipiec",
      "label_august": "sierpień",
      "label_september": "wrzesień",
      "label_october": "październik",
      "label_november": "listopad",
      "label_december": "grudzień",
      "label_departure": "Pogrzeb",
      "label_type": "Type",
      "label_weeks": "Tygodnie",
      "label_save": "Zapisz",
      "label_back": "Powrót",
      "label_nodate": "Brak daty",
      "label_schedule": "Godziny sprawowania",
      "label_show_visit": "Wyświetlaj wizyty duszpasterskie",
      "label_show_booking": "Wyświetlaj zaproszenia na wizytę duszpasterską",
      "label_firstname": "Imię",
      "label_surname": "Nazwisko",
      "label_donation": "Ofiara",
      "label_statistics": "Statystyki",
      "label_refresh": "Odśwież",
      "label_month": "Miesiąc",
      "label_begining": "Początek",
      "label_date": "Data",
      "label_day": "Dzień",
      "label_title_confirm": "Potwierdź",
      "help_description": "",
      "help_scheduled": "",
      "help_value": "",
      "help_notes": "",
      "help_id": "",
      "help_type": "",
      "help_firstname": "",
      "help_surname": "",
      "help_street": "",
      "help_number": "",
      "help_city": "",
      "help_donation": ""
    }
  }
}
